### PR TITLE
Privacy Policy

### PR DESCRIPTION
**Pull request by ghost**
So, I copied an existing privacy policy and modified it to fit our needs.

@HaywoodSolutions  @HenryBrown0  You may wish to have a quick read over it to make sure it's all good.

All the GDPR specific stuff is handled by the user emailing us to do the various things. The Data Access request will require a reply to be sent to the person who sent the email.

### CODE REVIEW

**Comment by HenryBrown0** [comment]
@HaywoodSolutions are you happy for the privacy policy to be in this repo or did you want it in a different one?

**Comment by HaywoodSolutions** [comment]
This seems fine, only thing is we might need to control where the platform can be accessed. So ideally we need something about before putting client online they require permission. Otherwise the Uni could say we are associated with any wrong doings of other clients out of our control. We could have a mention that you follow all the rules and conditions of kentflix.com/legal just to keep this in order.

**Comment by AluminiumTech** [comment]
sure

**Review by HenryBrown0 — APPROVED** [review]

**Comment by AluminiumTech** [comment]
@HaywoodSolutions @HenryBrown0  Since it's been approved, do one of you guys want to merge the changes?

**Comment by HenryBrown0** [comment]
@HaywoodSolutions waiting for your reviewing before merging

**Pull request merged**
